### ISSUE TITLE
TreeNode has allowsChildren variable, but no way to set/get it

### ISSUE THREAD

**Issue by Jazzepi** [yfpeng/pengyifan-commons#3]
The TreeNode class has an `allowsChildren` variable that's not settable, or gettable, rendering it a not-very-helpful constant of `true`. There's also mention in the Javadocs of the `getAllowsChildren` method which does not exist, on the `isLeaf` method.

**Comment by yfpeng** [comment]
You are right. `allowsChildren` is never used. I dont think it will be, so removed it from `TreeNode`.

Thanks for pointing this out.

**Comment by Jazzepi** [comment]
No problem :) I like the library so I just wanted to give back if I could.
